# build manifest for builds.sr.ht

image: archlinux
packages:
        - png
        - tiff
        - jpeg
sources:
        - https://git.sr.ht/~coco/imscript/
tasks:
        - build: make -C imscript
        - test: make -C imscript test
